/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [
    // Set default CSS variables on the `:root` element
    ({ addBase }) =>
      addBase({
        ":root": {
          // Light mode colors (cooking app theme with emerald primary and warm neutrals)
          "--background": "oklch(1 0 0)",
          "--foreground": "oklch(0.35 0 0)",
          "--card": "oklch(0.98 0 0)",
          "--card-foreground": "oklch(0.25 0 0)",
          "--popover": "oklch(1 0 0)",
          "--popover-foreground": "oklch(0.25 0 0)",
          "--primary": "oklch(0.726 0.100 144.1)",
          "--primary-foreground": "oklch(1 0 0)",
          "--secondary": "oklch(0.718 0.170 29.5)",
          "--secondary-foreground": "oklch(1 0 0)",
          "--muted": "oklch(0.96 0 0)",
          "--muted-foreground": "oklch(0.45 0 0)",
          "--accent": "oklch(0.686 0.158 151.5)",
          "--accent-foreground": "oklch(1 0 0)",
          "--destructive": "oklch(0.55 0.22 25)",
          "--destructive-foreground": "oklch(1 0 0)",
          "--border": "oklch(0.92 0 0)",
          "--input": "oklch(0.98 0 0)",
          "--ring": "oklch(0.45 0.15 160)",
          "--chart-1": "oklch(0.45 0.15 160)",
          "--chart-2": "oklch(0.55 0.12 160)",
          "--chart-3": "oklch(0.65 0.18 45)",
          "--chart-4": "oklch(0.55 0.15 200)",
          "--chart-5": "oklch(0.55 0.22 25)",
          "--radius": "0.5rem",
          "--sidebar": "oklch(0.96 0 0)",
          "--sidebar-foreground": "oklch(0.25 0 0)",
          "--sidebar-primary": "oklch(0.45 0.15 160)",
          "--sidebar-primary-foreground": "oklch(1 0 0)",
          "--sidebar-accent": "oklch(0.55 0.12 160)",
          "--sidebar-accent-foreground": "oklch(1 0 0)",
          "--sidebar-border": "oklch(0.92 0 0)",
          "--sidebar-ring": "oklch(0.45 0.15 160)",
        },
        ".dark": {
          // Dark mode colors (maintaining cooking app theme)
          "--background": "oklch(0.08 0 0)",
          "--foreground": "oklch(0.95 0 0)",
          "--card": "oklch(0.12 0 0)",
          "--card-foreground": "oklch(0.95 0 0)",
          "--popover": "oklch(0.08 0 0)",
          "--popover-foreground": "oklch(0.95 0 0)",
          "--primary": "oklch(0.55 0.12 160)",
          "--primary-foreground": "oklch(0.08 0 0)",
          "--secondary": "oklch(0.18 0 0)",
          "--secondary-foreground": "oklch(0.95 0 0)",
          "--muted": "oklch(0.18 0 0)",
          "--muted-foreground": "oklch(0.65 0 0)",
          "--accent": "oklch(0.55 0.12 160)",
          "--accent-foreground": "oklch(0.08 0 0)",
          "--destructive": "oklch(0.55 0.22 25)",
          "--destructive-foreground": "oklch(0.95 0 0)",
          "--border": "oklch(0.18 0 0)",
          "--input": "oklch(0.18 0 0)",
          "--ring": "oklch(0.55 0.12 160)",
          "--chart-1": "oklch(0.55 0.12 160)",
          "--chart-2": "oklch(0.65 0.15 160)",
          "--chart-3": "oklch(0.75 0.18 45)",
          "--chart-4": "oklch(0.65 0.15 200)",
          "--chart-5": "oklch(0.65 0.22 25)",
          "--sidebar": "oklch(0.12 0 0)",
          "--sidebar-foreground": "oklch(0.95 0 0)",
          "--sidebar-primary": "oklch(0.55 0.12 160)",
          "--sidebar-primary-foreground": "oklch(0.08 0 0)",
          "--sidebar-accent": "oklch(0.18 0 0)",
          "--sidebar-accent-foreground": "oklch(0.95 0 0)",
          "--sidebar-border": "oklch(0.18 0 0)",
          "--sidebar-ring": "oklch(0.55 0.12 160)",
        },
      }),
  ],
}